export default {
  plowing: {
    done: false,
    planing: false,
    planingDate: null,
    consumption: 40,
    paid: false,
    paidPrice: 10000,
  },

  disking: {
    done: false,
    planing: true,
    planingDate: null,
    consumption: 30,
    paid: true,
    paidPrice: 10000,
  },

  horrowing: {
    done: false,
    planing: true,
    planingDate: null,
    consumption: 40,
    paid: false,
    paidPrice: 10000,
  },

  harvesting: {
    done: false,
    planing: true,
    planingDate: null,
    consumption: 40,
    paid: false,
    paidPrice: 10000,
  },
  sowing: {
    done: false,
    planing: true,
    planingDate: null,
    consumption: 40,
    paid: false,
    paidPrice: 10000,
  },
  fertilization1: {
    done: false,
    planing: true,
    planingDate: null,
    consumption: 40,
    paid: false,
    paidPrice: 10000,
  },
  fertilization2: {
    done: false,
    planing: true,
    planingDate: null,
    consumption: 40,
    paid: false,
    paidPrice: 10000,
  },
  spraying1: {
    done: false,
    planing: true,
    planingDate: null,
    consumption: 40,
    paid: false,
    paidPrice: 10000,
  },
  spraying2: {
    done: false,
    planing: true,
    planingDate: null,
    consumption: 40,
    paid: false,
    paidPrice: 10000,
  },
};
